### ISSUE TITLE
Dataset too large to browse

### ISSUE THREAD

**Issue by EntilZha** [huggingface/nlp-viewer#3]
Hi, not sure if the best place to ask is here or the nlp repo.

A few weeks back ago I contributed the qanta dataset https://huggingface.co/nlp/viewer/?dataset=qanta&config=mode%3Dfull%2Cchar_skip%3D25, but noticed that it can't be displayed. Are there configuration changes on the viewer or changes in the data that would let it load?

It looks like the dataset is on the boundary of being renderable since it loads on the "first" configuration, but not "full". The only difference for these subsets is that the `text` field has the content of the `full_question` field instead of `first_sentence`. Perhaps an alternative is to change which configuration is the default though. Thanks!

**Comment by srush** [comment]
Neat dataset. 

It seems like this check is failing: 

>  builder_instance.info.size_in_bytes is not None
            
Do you see the same on your side?

**Comment by EntilZha** [comment]
I gave a shot at loading the viewer locally but get this error.

```python
File "/home/entilzha/.cache/pypoetry/virtualenvs/nlp-viewer-sNOfz1Ov-py3.8/lib/python3.8/site-packages/streamlit/ScriptRunner.py", line 322, in _run_script
    exec(code, module.__dict__)
File "/home/entilzha/code/nlp-viewer/run.py", line 55, in <module>
    app_state = st.experimental_get_query_string(
```

After poking around some issues, it seems like this PR (https://github.com/streamlit/streamlit/pull/1169) hasn't been merged, but assumed the nlp-viewer code is based on this commit. After a bit of whacamole I got an instance running on my machine get the trace below. I'm guessing I have some version mismatch somewhere. I was able to run the snippet below though to get that info.

```python
opt = 'qanta'
conf = 'mode=full,char_skip=25'
module_path = nlp.load.prepare_module(opt, dataset=True)
builder_cls = nlp.load.import_main_class(module_path, dataset=True)
builder_instance = builder_cls(name=conf)
print(builder_instance.info.size_in_bytes)
# 382184742
# 40000000000 <-- max
```

I put in some print statements to check this line https://github.com/huggingface/nlp-viewer/blob/34f9b1156df9837cad26408a4e4e7fd0c65b9a26/run.py#L188
 and get this:
```
type(dts): <class 'dict'>
dts: {'guesstrain': Dataset(schema: {'id': 'string', 'qanta_id': 'int32', 'proto_id': 'string', 'qdb_id': 'int32', 'dataset': ..., num_rows: 1145)}
fail: False
```
which is odd and doesn't really explain the other error (although it explains the subsequent JSON probably). Not sure what I'm missing here on not reproducing. 


Error from above, that I don't think matters:
```
TypeError: Object of type ndarray is not JSON serializable
Traceback:
File "/home/entilzha/.local/lib/python3.8/site-packages/streamlit/ScriptRunner.py", line 322, in _run_script
    exec(code, module.__dict__)
File "/home/entilzha/code/nlp-viewer/run.py", line 271, in <module>
    out = json.dumps(v, indent=2, sort_keys=True)
File "/usr/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
File "/usr/lib/python3.8/json/encoder.py", line 201, in encode
    chunks = list(chunks)
File "/usr/lib/python3.8/json/encoder.py", line 438, in _iterencode
    o = _default(o)
File "/usr/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
```

**Comment by srush** [comment]
Oh wow, thanks for doing all this work. Yeah, I'm running a patched streamlit because they are super slow. Sorry, I should have warned you.  

I will look at it more next week and see what's going on. I must have a miscached version of these datasets.

**Comment by EntilZha** [comment]
NP, I did clear my dataset cache if that helps (from when I initially submitted the PR for qanta in nlp package).

**Comment by srush** [comment]
Fixed now.
